### ISSUE TITLE
[FEAT] 공통 응답 포맷 클래스 추가

### ISSUE THREAD

**Issue by eunji8784** [mapo18-1/zero#3]
## Feature Request check list ✅

- [x] 이슈 제목: [FEAT] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요 ✨

- 조회(GET) 메소드 API 구현 시 응답 데이터의 형식을 일관성 있게 포맷팅하기 위한 클래스를 정의합니다. 공통으로 적용되는 코드이므로 /common 폴더 안에 생성합니다.

## TODO 📝

- [ ] ApiResponse 클래스 정의
- [ ] Error, Success, StatusCode를 위한 enum 타입 클래스 정의
